CREATE DATABASE IF NOT EXISTS `app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `app`;

CREATE TABLE IF NOT EXISTS `payment_entity` (
  `id` VARBINARY(16) NOT NULL,
  `status` VARCHAR(255) DEFAULT NULL,
  `amount` BIGINT DEFAULT NULL,
  `created` DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  `transaction_id` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `credit_request_entity` (
  `id` VARBINARY(16) NOT NULL,
  `status` VARCHAR(255) DEFAULT NULL,
  `bank_id` VARCHAR(255) DEFAULT NULL,
  `created` DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;